import { Country } from "@/types/country";

export const countries: Country[] = [
  {
    name: "France",
    code: "FR",
    flagColors: ["blue", "white", "red"],
    capital: "Paris",
    cuisine: ["Croissants", "Baguettes", "Coq au Vin"],
    sports: ["Football", "Rugby", "Cycling"],
    landmarks: ["Eiffel Tower", "Louvre Museum", "Palace of Versailles"],
    historicalEvents: [
      "French Revolution (1789)",
      "Napoleon Era",
      "Liberation of Paris (1944)",
    ],
    famousPersonalities: ["Napoleon Bonaparte", "Marie Curie", "Victor Hugo"],
    traditions: ["Bastille Day", "Wine Making", "Fashion Week"],
    continent: "Europe",
  },
  {
    name: "Kenya",
    code: "KE",
    flagColors: ["black", "red", "green", "white"],
    capital: "Nairobi",
    cuisine: ["Ugali", "Nyama Choma", "Sukuma Wiki"],
    sports: ["Athletics", "Rugby", "Football"],
    landmarks: ["Mount Kenya", "Masai Mara", "Lake Victoria"],
    historicalEvents: [
      "Independence (1963)",
      "Mau Mau Uprising",
      "First African Woman Nobel Peace Prize",
    ],
    famousPersonalities: [
      "Wangari Maathai",
      "Lupita Nyong'o",
      "Eliud Kipchoge",
    ],
    traditions: ["Maasai Culture", "Tribal Dances", "Beadwork"],
    continent: "Africa",
  },
  {
    name: "Japan",
    code: "JP",
    flagColors: ["white", "red"],
    capital: "Tokyo",
    cuisine: ["Sushi", "Ramen", "Tempura"],
    sports: ["Sumo", "Baseball", "Judo"],
    landmarks: ["Mount Fuji", "Tokyo Tower", "Fushimi Inari Shrine"],
    historicalEvents: ["Meiji Restoration", "World War II", "Economic Miracle"],
    famousPersonalities: [
      "Akira Kurosawa",
      "Hayao Miyazaki",
      "Emperor Hirohito",
    ],
    traditions: ["Tea Ceremony", "Hanami", "Kimono Wearing"],
    continent: "Asia",
  },
  {
    name: "Afghanistan",
    code: "AF",
    flagColors: ["black", "red", "green"],
    capital: "Kabul",
    cuisine: ["Kabuli Pulao", "Mantu", "Ashak"],
    sports: ["Cricket", "Football", "Buzkashi"],
    landmarks: ["Buddhas of Bamiyan", "Kabul Museum", "Minaret of Jam"],
    historicalEvents: ["Soviet-Afghan War", "Civil War", "Taliban Rule"],
    famousPersonalities: [
      "Malala Yousafzai",
      "Khaled Hosseini",
      "Ahmad Shah Durrani",
    ],
    traditions: ["Nowruz", "Eid al-Fitr", "Pashto Poetry"],
    continent: "Asia",
  },
  {
    name: "Albania",
    code: "AL",
    flagColors: ["red", "black"],
    capital: "Tirana",
    cuisine: ["Fërgesë", "Byrek", "Tavë Kosi"],
    sports: ["Football", "Basketball", "Weightlifting"],
    landmarks: ["Butrint", "Gjirokastër", "Shkodra Castle"],
    historicalEvents: [
      "Independence (1912)",
      "Communist Regime",
      "Transition to Democracy",
    ],
    famousPersonalities: ["Ismail Kadare", "Mother Teresa", "Dritëro Agolli"],
    traditions: ["Bajram", "Dita e Verës", "Folklore Festivals"],
    continent: "Europe",
  },
  {
    name: "Algeria",
    code: "DZ",
    flagColors: ["green", "white", "red"],
    capital: "Algiers",
    cuisine: ["Couscous", "Chakhchoukha", "Mechoui"],
    sports: ["Football", "Handball", "Basketball"],
    landmarks: ["Algiers Casbah", "Hoggar Mountains", "Tassili n'Ajjer"],
    historicalEvents: [
      "Independence (1962)",
      "Algerian War of Independence",
      "Civil War",
    ],
    famousPersonalities: ["Albert Camus", "Assia Djebar", "Houari Boumediene"],
    traditions: ["Eid al-Fitr", "Mouloud", "Aïd el-Adha"],
    continent: "Africa",
  },
  {
    name: "Andorra",
    code: "AD",
    flagColors: ["blue", "yellow", "red"],
    capital: "Andorra la Vella",
    cuisine: ["Trinxat", "Escudella", "Canelons"],
    sports: ["Football", "Basketball", "Skiing"],
    landmarks: ["Grandvalira", "Casa de la Vall", "Sant Joan de Caselles"],
    historicalEvents: [
      "Co-principality established",
      "Spanish Civil War",
      "Tourism boom in the 20th century",
    ],
    famousPersonalities: ["Julià Reig", "Nicolau d'Olwer", "Josep Maria Soler"],
    traditions: ["Andorran National Day", "Carnival", "Fires of Sant Joan"],
    continent: "Europe",
  },
  {
    name: "Angola",
    code: "AO",
    flagColors: ["red", "black", "yellow"],
    capital: "Luanda",
    cuisine: ["Muamba de Galinha", "Caldeirada", "Funge"],
    sports: ["Football", "Basketball", "Handball"],
    landmarks: [
      "Kissama National Park",
      "Fortaleza de São Miguel",
      "Luanda Island",
    ],
    historicalEvents: ["Independence (1975)", "Civil War", "Oil Boom"],
    famousPersonalities: [
      "Agostinho Neto",
      "Aldemiro de Almeida",
      "Marcolino Gomes Candau",
    ],
    traditions: ["Carnival", "Festa de São João", "Cultural Festivals"],
    continent: "Africa",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flagColors: ["red", "blue", "white"],
    capital: "Saint John's",
    cuisine: ["Fungee and Pepperpot", "Ducana", "Saltfish"],
    sports: ["Cricket", "Football", "Netball"],
    landmarks: ["Nelson's Dockyard", "Shirley Heights", "Devil's Bridge"],
    historicalEvents: [
      "Independence (1981)",
      "Colonial History",
      "Tourism Development",
    ],
    famousPersonalities: [
      "V. C. Bird",
      "Bishop Desmond Tutu",
      "Sir Vivian Richards",
    ],
    traditions: [
      "Carnival",
      "Antigua Sailing Week",
      "Independence Day Celebrations",
    ],
    continent: "North America",
  },
  {
    name: "Argentina",
    code: "AR",
    flagColors: ["light blue", "white"],
    capital: "Buenos Aires",
    cuisine: ["Asado", "Empanadas", "Dulce de Leche"],
    sports: ["Football", "Basketball", "Rugby"],
    landmarks: ["Iguazu Falls", "Perito Moreno Glacier", "Casa Rosada"],
    historicalEvents: ["Independence (1816)", "Dirty War", "Economic Crisis"],
    famousPersonalities: ["Lionel Messi", "Evita Perón", "Jorge Luis Borges"],
    traditions: ["Tango", "Mate", "Fiesta de la Vendimia"],
    continent: "South America",
  },
  {
    name: "Armenia",
    code: "AM",
    flagColors: ["red", "blue", "orange"],
    capital: "Yerevan",
    cuisine: ["Khorovats", "Dolma", "Lavash"],
    sports: ["Football", "Chess", "Wrestling"],
    landmarks: ["Geghard Monastery", "Lake Sevan", "Khor Virap"],
    historicalEvents: [
      "Independence (1991)",
      "Armenian Genocide",
      "Soviet Era",
    ],
    famousPersonalities: [
      "Serj Tankian",
      "Hovhannes Shiraz",
      "Aram Khachaturian",
    ],
    traditions: ["Vardavar", "Armenian Christmas", "Khachkar"],
    continent: "Asia",
  },
  {
    name: "Australia",
    code: "AU",
    flagColors: ["blue", "red", "white"],
    capital: "Canberra",
    cuisine: ["Vegemite", "Pavlova", "Lamington"],
    sports: ["Cricket", "Rugby", "Australian Rules Football"],
    landmarks: ["Sydney Opera House", "Great Barrier Reef", "Uluru"],
    historicalEvents: [
      "Federation (1901)",
      "World War I",
      "Indigenous Rights Movement",
    ],
    famousPersonalities: ["Steve Irwin", "Cate Blanchett", "Hugh Jackman"],
    traditions: ["Australia Day", "ANZAC Day", "Christmas in July"],
    continent: "Oceania",
  },
  {
    name: "Austria",
    code: "AT",
    flagColors: ["red", "white"],
    capital: "Vienna",
    cuisine: ["Wiener Schnitzel", "Sachertorte", "Apfelstrudel"],
    sports: ["Skiing", "Football", "Ice Hockey"],
    landmarks: [
      "Schönbrunn Palace",
      "St. Stephen's Cathedral",
      "Hohensalzburg Fortress",
    ],
    historicalEvents: [
      "Austro-Hungarian Empire",
      "World War I",
      "Neutrality Post-WWII",
    ],
    famousPersonalities: [
      "Wolfgang Amadeus Mozart",
      "Ludwig van Beethoven",
      "Sigmund Freud",
    ],
    traditions: ["Christmas Markets", "Vienna Ball", "Oktoberfest"],
    continent: "Europe",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    flagColors: ["blue", "red", "green"],
    capital: "Baku",
    cuisine: ["Plov", "Dolma", "Kebabs"],
    sports: ["Football", "Wrestling", "Chess"],
    landmarks: [
      "Flame Towers",
      "Old City (Icherisheher)",
      "Gobustan National Park",
    ],
    historicalEvents: [
      "Independence (1991)",
      "Oil Boom",
      "Nagorno-Karabakh Conflict",
    ],
    famousPersonalities: ["Gara Garayev", "Nizami Ganjavi", "Heydar Aliyev"],
    traditions: [
      "Novruz Bayram",
      "Goychay Pomegranate Festival",
      "Azerbaijani Mugham",
    ],
    continent: "Asia",
  },
  {
    name: "The Bahamas",
    code: "BS",
    flagColors: ["black", "gold", "aquamarine"],
    capital: "Nassau",
    cuisine: ["Conch Fritters", "Rock Lobsters", "Bahamian Macaroni"],
    sports: ["Basketball", "Cricket", "Track and Field"],
    landmarks: ["Blue Hole", "Exuma Cays", "Nassau Straw Market"],
    historicalEvents: [
      "Independence (1973)",
      "Colonial History",
      "Tourism Development",
    ],
    famousPersonalities: [
      "Sir Sidney Poitier",
      "Lynden Pindling",
      "Mychal Thompson",
    ],
    traditions: [
      "Junkanoo",
      "Bahamian Independence Day",
      "Bahamian Music Festivals",
    ],
    continent: "North America",
  },
  {
    name: "Bahrain",
    code: "BH",
    flagColors: ["red", "white"],
    capital: "Manama",
    cuisine: ["Machboos", "Muhammar", "Bahraini Falafel"],
    sports: ["Football", "Basketball", "Motorsport"],
    landmarks: ["Bahrain Fort", "Qal'at al-Bahrain", "Tree of Life"],
    historicalEvents: [
      "Independence (1971)",
      "Pearl Diving Industry",
      "Arab Spring",
    ],
    famousPersonalities: [
      "Hamad bin Isa Al Khalifa",
      "Bahrain's National Poet",
      "Nasser Al-Attiyah",
    ],
    traditions: ["Bahraini National Day", "Eid al-Fitr", "Ashura"],
    continent: "Asia",
  },
  {
    name: "Bangladesh",
    code: "BD",
    flagColors: ["green", "red"],
    capital: "Dhaka",
    cuisine: ["Biryani", "Hilsa Fish", "Pitha"],
    sports: ["Cricket", "Football", "Kabaddi"],
    landmarks: ["Sundarbans", "Cox's Bazar", "Lalbagh Fort"],
    historicalEvents: [
      "Independence (1971)",
      "Language Movement",
      "Liberation War",
    ],
    famousPersonalities: [
      "Rabindranath Tagore",
      "Sheikh Mujibur Rahman",
      "Muhammad Yunus",
    ],
    traditions: ["Pohela Boishakh", "Ekushey Book Fair", "Durga Puja"],
    continent: "Asia",
  },
  {
    name: "Barbados",
    code: "BB",
    flagColors: ["blue", "gold"],
    capital: "Bridgetown",
    cuisine: ["Flying Fish", "Cou-Cou", "Macaroni Pie"],
    sports: ["Cricket", "Football", "Rugby"],
    landmarks: ["Harrison's Cave", "St. Nicholas Abbey", "Bathsheba Beach"],
    historicalEvents: [
      "Independence (1966)",
      "Colonial History",
      "Tourism Development",
    ],
    famousPersonalities: ["Rihanna", "Sir Garfield Sobers", "Errol Barrow"],
    traditions: ["Crop Over Festival", "Oistins Fish Fry", "Kadooment Day"],
    continent: "North America",
  },
  {
    name: "Belarus",
    code: "BY",
    flagColors: ["red", "green", "white"],
    capital: "Minsk",
    cuisine: ["Draniki", "Babka", "Kholodnik"],
    sports: ["Ice Hockey", "Football", "Basketball"],
    landmarks: ["Mir Castle", "Brest Hero-Fortress", "Nesvizh Castle"],
    historicalEvents: [
      "Independence (1991)",
      "Soviet Era",
      "Chernobyl Disaster",
    ],
    famousPersonalities: [
      "Marc Chagall",
      "Svetlana Alexievich",
      "Maxim Bogdanovich",
    ],
    traditions: ["Kupalle", "Maslenitsa", "Dziady"],
    continent: "Europe",
  },
  {
    name: "Belgium",
    code: "BE",
    flagColors: ["black", "yellow", "red"],
    capital: "Brussels",
    cuisine: ["Moules-frites", "Belgian Waffles", "Chocolate"],
    sports: ["Football", "Cycling", "Field Hockey"],
    landmarks: ["Atomium", "Grand Place", "Manneken Pis"],
    historicalEvents: [
      "Independence (1830)",
      "World War I",
      "European Union Formation",
    ],
    famousPersonalities: ["René Magritte", "Hergé", "Eddy Merckx"],
    traditions: [
      "Carnival of Binche",
      "Brussels Flower Carpet",
      "Saint Nicholas Day",
    ],
    continent: "Europe",
  },
  {
    name: "Benin",
    code: "BJ",
    flagColors: ["green", "yellow", "red"],
    capital: "Porto-Novo",
    cuisine: ["Pâte", "Amiwo", "Akassa"],
    sports: ["Football", "Basketball", "Athletics"],
    landmarks: [
      "Ouidah Museum of History",
      "Royal Palace of Abomey",
      "Pendjari National Park",
    ],
    historicalEvents: [
      "Independence (1960)",
      "Dahomey Kingdom",
      "Political Turmoil",
    ],
    famousPersonalities: [
      "Thomas Sankara",
      "Sébastien Ajavon",
      "Mireille Gansou",
    ],
    traditions: ["Voodoo Festival", "Benin National Day", "Cultural Festivals"],
    continent: "Africa",
  },
  {
    name: "Bhutan",
    code: "BT",
    flagColors: ["orange", "yellow"],
    capital: "Thimphu",
    cuisine: ["Ema Datshi", "Phaksha Paa", "Jasha Maru"],
    sports: ["Archery", "Football", "Basketball"],
    landmarks: ["Tiger's Nest Monastery", "Punakha Dzong", "Buddha Dordenma"],
    historicalEvents: [
      "Independence (1907)",
      "Democratic Transition (2008)",
      "Cultural Preservation",
    ],
    famousPersonalities: [
      "Jigme Khesar Namgyel Wangchuck",
      "Zhabdrung Ngawang Namgyal",
      "Karma Chagme",
    ],
    traditions: ["Tshechu Festival", "Losar", "Archery Festivals"],
    continent: "Asia",
  },
  {
    name: "Bolivia",
    code: "BO",
    flagColors: ["red", "yellow", "green"],
    capital: "Sucre",
    cuisine: ["Salteñas", "Pique Macho", "Ceviche"],
    sports: ["Football", "Basketball", "Cycling"],
    landmarks: ["Salar de Uyuni", "Lake Titicaca", "Tiwanaku"],
    historicalEvents: [
      "Independence (1825)",
      "Cochabamba Water War",
      "Political Changes",
    ],
    famousPersonalities: [
      "Simón Bolívar",
      "Evo Morales",
      "María Luisa Bemberg",
    ],
    traditions: ["Carnaval de Oruro", "Inti Raymi", "Day of the Dead"],
    continent: "South America",
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    flagColors: ['blue', 'yellow', 'white'],
    capital: 'Sarajevo',
    cuisine: ['Ćevapi', 'Sogan-dolma', 'Baklava'],
    sports: ['Football', 'Basketball', 'Handball'],
    landmarks: ['Stari Most', 'Baščaršija', 'Srebrenica Memorial'],
    historicalEvents: ['Independence (1992)', 'Bosnian War', 'Dayton Agreement'],
    famousPersonalities: ['Ivo Andrić', 'Goran Ivanišević', 'Marina Abramović'],
    traditions: ['Bajram', 'New Year', 'Sarajevo Film Festival'],
    continent: 'Europe',
  },
  {
    name: 'Botswana',
    code: 'BW',
    flagColors: ['blue', 'black', 'white'],
    capital: 'Gaborone',
    cuisine: ['Seswaa', 'Pap', 'Biltong'],
    sports: ['Football', 'Rugby', 'Cricket'],
    landmarks: ['Okavango Delta', 'Chobe National Park', 'Tsodilo Hills'],
    historicalEvents: ['Independence (1966)', 'Bechuanaland Protectorate', 'Democratic Governance'],
    famousPersonalities: ['Seretse Khama', 'Desmond Tutu', 'Bessie Head'],
    traditions: ['Dikhwaere', 'Batswana Cultural Festivals', 'Traditional Music'],
    continent: 'Africa',
  },
  {
    name: 'Brazil',
    code: 'BR',
    flagColors: ['green', 'yellow', 'blue'],
    capital: 'Brasília',
    cuisine: ['Feijoada', 'Pão de Queijo', 'Brigadeiro'],
    sports: ['Football', 'Volleyball', 'Basketball'],
    landmarks: ['Christ the Redeemer', 'Amazon Rainforest', 'Iguazu Falls'],
    historicalEvents: ['Independence (1822)', 'Military Dictatorship', 'Democratic Transition'],
    famousPersonalities: ['Pelé', 'Ayrton Senna', 'Joaquim Nabuco'],
    traditions: ['Carnival', 'Festa Junina', 'New Year\'s Eve'],
    continent: 'South America',
  },
  {
    name: 'Brunei',
    code: 'BN',
    flagColors: ['black', 'yellow'],
    capital: 'Bandar Seri Begawan',
    cuisine: ['Nasi Lemak', 'Satay', 'Ambuyat'],
    sports: ['Football', 'Badminton', 'Sepak Takraw'],
    landmarks: ['Sultan Omar Ali Saifuddien Mosque', 'Jame\' Asr Hassanil Bolkiah Mosque', 'Ulu Temburong National Park'],
    historicalEvents: ['Independence (1984)', 'British Protectorate', 'Sultanate History'],
    famousPersonalities: ['Sultan Hassanal Bolkiah', 'Yusof bin Ishak', 'Abdul Razak'],
    traditions: ['Hari Raya Aidilfitri', 'Brunei National Day', 'Royal Brunei Day'],
    continent: 'Asia',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    flagColors: ['white', 'green', 'red'],
    capital: 'Sofia',
    cuisine: ['Banitsa', 'Shopska Salad', 'Kiselo Mlyako'],
    sports: ['Football', 'Volleyball', 'Weightlifting'],
    landmarks: ['Alexander Nevsky Cathedral', 'Rila Monastery', 'Plovdiv Old Town'],
    historicalEvents: ['Independence (1908)', 'Communist Era', 'EU Membership (2007)'],
    famousPersonalities: ['Hristo Stoichkov', 'Baba Vanga', 'Dimitar Berbatov'],
    traditions: ['Baba Marta', 'Kukeri', 'Nestinarstvo'],
    continent: 'Europe',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    flagColors: ['red', 'green', 'yellow'],
    capital: 'Ouagadougou',
    cuisine: ['Riz Gras', 'To', 'Benga'],
    sports: ['Football', 'Basketball', 'Athletics'],
    landmarks: ['Laongo Sculpture Symposium', 'Gorom-Gorom Market', 'Bobo Dioulasso'],
    historicalEvents: ['Independence (1960)', 'Revolution of 1983', 'Political Instability'],
    famousPersonalities: ['Thomas Sankara', 'Blaise Compaoré', 'Joseph Ki-Zerbo'],
    traditions: ['Fasogho Festival', 'Nuit de la Culture', 'International Festival of Arts'],
    continent: 'Africa',
  },
  {
    name: 'Burundi',
    code: 'BI',
    flagColors: ['red', 'green', 'white'],
    capital: 'Gitega',
    cuisine: ['Bujumbura Fish', 'Isombe', 'Brochettes'],
    sports: ['Football', 'Cycling', 'Athletics'],
    landmarks: ['Lake Tanganyika', 'Gitega Museum', 'Rusizi National Park'],
    historicalEvents: ['Independence (1962)', 'Civil War', 'Ethnic Conflict'],
    famousPersonalities: ['Pierre Nkurunziza', 'Melchior Ndadaye', 'Sonia Rolland'],
    traditions: ['Umuganuro', 'Intore Dance', 'Burundian New Year'],
    continent: 'Africa',
  },
  // Add more countries here
];